services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: zenith-file-saver-local
    ports:
      - "8080:8080"
    volumes:
      - ../data:/app/data
      - ../FILES:/app/FILES
    env_file:
      - ../.env
    environment:
      - TZ=America/Sao_Paulo # Configure correct timezone for file dates
    restart: unless-stopped
